[build]
  command = "npm run build"
  publish = ".next"

[functions]
  included_files = ["**/*.js", "**/*.ts", "**/*.json"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[dev]
  command = "next dev"